/**
 * Initial Mock & Local State Store for Sage & Bloom Admin Panel
 * Styled & Structured for Dribbble-grade E-Commerce Experience
 */

export const INITIAL_METRICS = {
  totalRevenue: 12480.00,
  totalOrders: 242,
  totalCustomers: 312,
  totalProducts: 16,
  lowStockAlerts: 0,
  averageOrderValue: 51.57,
  processingTimeMin: 16,
  avgItemsPerOrder: 2.3,
  pendingRate: '0.32%',
  rejectRate: '0.51%',
  fulfillment: {
    totalFormatted: '$2.2k',
    totalOrdersCount: 242,
    shipmentsAmount: '$1,480.00',
    shipmentsCount: 147,
    pickupsAmount: '$766.00',
    pickupsCount: 95,
  },
  orderStatusBreakdown: [
    { status: 'Paid', percentage: 89, color: '#4D5E43' },
    { status: 'Processing', percentage: 8, color: '#C9A227' },
    { status: 'Cancelled', percentage: 2, color: '#9C6D62' },
    { status: 'Refunded', percentage: 1, color: '#7B8C6E' },
  ],
  monthlyRevenue: [
    { month: 'Apr', revenue: 6400, orders: 82 },
    { month: 'May', revenue: 7800, orders: 96 },
    { month: 'Jun', revenue: 9200, orders: 110 },
    { month: 'Jul', revenue: 10500, orders: 124 },
    { month: 'Aug', revenue: 11800, orders: 138 },
    { month: 'Sep', revenue: 12480, orders: 148 },
  ]
};

export const INITIAL_TOP_SELLERS = [
  {
    id: 'top-1',
    title: 'Woodland Herbal Bar',
    subtitle: 'Rustic Oat & Shea Butter',
    salesCount: 64,
    revenue: '₹22,336',
    imageUrl: '/images/Natural_Soap_And_Bath_Bomb.webp',
    category: 'Botanical Herbal'
  },
  {
    id: 'top-2',
    title: 'Lavender & Rose Garden Set',
    subtitle: '5-Bar Artisan Botanical Set',
    salesCount: 52,
    revenue: '₹31,148',
    imageUrl: '/images/soap_2.jpg',
    category: 'Floral & Rose'
  },
  {
    id: 'top-3',
    title: 'Oatmeal & Honey Bar',
    subtitle: 'Raw Honey & Ground Oats',
    salesCount: 48,
    revenue: '₹15,792',
    imageUrl: '/images/soap_6.jpg',
    category: 'Nourishing & Honey'
  },
  {
    id: 'top-4',
    title: 'Relax & Enjoy Spa Ritual Box',
    subtitle: 'Luxury Self-Care Crate',
    salesCount: 39,
    revenue: '₹35,061',
    imageUrl: '/images/soap_21.jpg',
    category: 'Gift Sets & Bundles'
  },
];

export const INITIAL_CATEGORIES = [
  { id: 1, name: 'Botanical Herbal', slug: 'botanical-herbal', count: 8, description: 'Earthy herbs, rosemary, wild sage, and pine.' },
  { id: 2, name: 'Floral & Rose', slug: 'floral-rose', count: 6, description: 'Pink Himalayan rose, French lavender, and chamomile.' },
  { id: 3, name: 'Exfoliating & Purifying', slug: 'exfoliating-purifying', count: 5, description: 'Mineral clay, activated charcoal, and sea salt.' },
  { id: 4, name: 'Nourishing & Honey', slug: 'nourishing-honey', count: 4, description: 'Raw amber honey, oat milk, and organic shea butter.' },
  { id: 5, name: 'Gift Sets & Bundles', slug: 'gift-sets', count: 3, description: 'Curated gift boxes and botanical sampler collections.' }
];

export const INITIAL_ADMIN_PRODUCTS = [
  {
    id: 'p-001',
    title: 'Woodland Herbal Bar',
    subtitle: 'Rustic Oat & Shea Butter Bar',
    slug: 'woodland-herbal-bar',
    category: 'Botanical Herbal',
    categoryId: 1,
    price: 349.00,
    originalPrice: 399.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/Natural_Soap_And_Bath_Bomb.webp',
    badge: 'Herbal Soap',
    rating: 5.0,
    reviewCount: 42,
    scentProfile: 'Dried Wildflowers, Oat Milk, Essential Oils',
    skinType: 'Normal to dry skin',
    description: 'A rustic oat-and-shea bar finished with dried wildflowers for a calm, grounding wash.',
    isActive: true,
  },
  {
    id: 'p-002',
    title: 'Aloe & Mint Refresh',
    subtitle: 'Cooling Aloe & Fresh Mint Leaf',
    slug: 'aloe-mint-refresh',
    category: 'Botanical Herbal',
    categoryId: 1,
    price: 299.00,
    originalPrice: 349.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_3.jpg',
    badge: 'Herbal Soap',
    rating: 4.5,
    reviewCount: 37,
    scentProfile: 'Peppermint Essential Oil, Fresh Mint, Aloe',
    skinType: 'All skin types',
    description: 'A cooling aloe vera bar with fresh mint leaf, perfect for a refreshing morning wash.',
    isActive: true,
  },
  {
    id: 'p-003',
    title: 'Lavender & Rose Garden Set',
    subtitle: '5-Bar Artisan Botanical Collection',
    slug: 'lavender-rose-garden-set',
    category: 'Floral & Rose',
    categoryId: 2,
    price: 599.00,
    originalPrice: 699.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_2.jpg',
    badge: 'Floral Soap',
    rating: 5.0,
    reviewCount: 64,
    scentProfile: 'Lavender Buds, Rose Petals, Honey Citrus, Green Tea',
    skinType: 'Normal skin',
    description: 'A five-bar collection featuring lavender, honey citrus, exfoliating green tea and rose petal.',
    isActive: true,
  },
  {
    id: 'p-004',
    title: 'Daisy Bloom Bar',
    subtitle: 'Hand-Molded Daisy Floral Bar',
    slug: 'daisy-bloom-bar',
    category: 'Floral & Rose',
    categoryId: 2,
    price: 279.00,
    originalPrice: 320.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_14.jpg',
    badge: 'Floral Soap',
    rating: 4.5,
    reviewCount: 21,
    scentProfile: 'Chamomile Extract, Soft Daisy Blossom',
    skinType: 'Normal skin',
    description: 'Hand-molded daisy soaps with a soft floral scent, sweet enough to double as a bathroom accent.',
    isActive: true,
  },
  {
    id: 'p-005',
    title: 'Rose Petal Trio',
    subtitle: 'Hand-Carved Ribbon Roses',
    slug: 'rose-petal-trio',
    category: 'Floral & Rose',
    categoryId: 2,
    price: 399.00,
    originalPrice: 450.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_8.jpg',
    badge: 'Floral Soap · Gift',
    rating: 5.0,
    reviewCount: 29,
    scentProfile: 'Pure Rose Oil, Natural Damask Rose',
    skinType: 'Normal skin',
    description: 'Three hand-carved rose soaps tied with ribbon — a romantic, gift-ready favourite.',
    isActive: true,
  },
  {
    id: 'p-006',
    title: 'Oatmeal & Honey Bar',
    subtitle: 'Raw Honey & Ground Oats Layered Bar',
    slug: 'oatmeal-honey-bar',
    category: 'Nourishing & Honey',
    categoryId: 4,
    price: 329.00,
    originalPrice: 379.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_6.jpg',
    badge: 'Honey & Natural',
    rating: 5.0,
    reviewCount: 58,
    scentProfile: 'Raw Forest Honey, Golden Oats, Warm Vanilla',
    skinType: 'Normal to dry skin',
    description: 'A cozy, golden bar layered with real oats and a drizzle of honey for a comforting soak.',
    isActive: true,
  },
  {
    id: 'p-007',
    title: 'Green Grape Cluster Soap',
    subtitle: 'Hand-Molded Grape Seed Glycerin Bar',
    slug: 'green-grape-cluster-soap',
    category: 'Nourishing & Honey',
    categoryId: 4,
    price: 349.00,
    originalPrice: 399.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_7.jpg',
    badge: 'Honey & Natural',
    rating: 4.5,
    reviewCount: 18,
    scentProfile: 'Grape Seed Extract, Light Crisp Fruit',
    skinType: 'Normal skin',
    description: 'A playful hand-molded grape cluster bar with a light, fruity fragrance.',
    isActive: true,
  },
  {
    id: 'p-008',
    title: 'Sea Mint Massage Bar',
    subtitle: 'Textured Nub Exfoliating Bar',
    slug: 'sea-mint-massage-bar',
    category: 'Exfoliating & Purifying',
    categoryId: 3,
    price: 379.00,
    originalPrice: 429.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_5.jpg',
    badge: 'Moisturizing',
    rating: 4.5,
    reviewCount: 15,
    scentProfile: 'Sea Salt, Peppermint Essential Oil, Shea',
    skinType: 'Normal to oily skin',
    description: 'A textured massage bar with raised nubs to gently buff while you wash.',
    isActive: true,
  },
  {
    id: 'p-009',
    title: 'Wildflower Glycerin Bar',
    subtitle: 'Real Pressed Suspended Wildflowers',
    slug: 'wildflower-glycerin-bar',
    category: 'Gift Sets & Bundles',
    categoryId: 5,
    price: 449.00,
    originalPrice: 499.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_4.jpg',
    badge: 'Special Edition',
    rating: 5.0,
    reviewCount: 33,
    scentProfile: 'Pressed Botanical Petals, Vitamin E',
    skinType: 'Normal skin',
    description: 'Crystal-clear glycerin soap with real pressed wildflowers suspended inside — a true statement piece.',
    isActive: true,
  },
  {
    id: 'p-010',
    title: 'Ocean Bliss Sliding Box Soap Trio',
    subtitle: 'Terrazzo Stone Soap & Keepsake Box',
    slug: 'ocean-bliss-sliding-box-soap-trio',
    category: 'Gift Sets & Bundles',
    categoryId: 5,
    price: 699.00,
    originalPrice: 799.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/ocean_bliss_trio.jpg',
    badge: 'Artisan Gift Set',
    rating: 5.0,
    reviewCount: 38,
    scentProfile: 'Ocean Breeze, Marine Botanicals, Sea Clay',
    skinType: 'All skin types',
    description: 'A set of three arched sliding keepsake drawer boxes featuring handcrafted terrazzo stone soaps with delicate seashell, coral, and seaweed botanical illustrations.',
    isActive: true,
  },
  {
    id: 'p-011',
    title: 'Little Explorers Animal Set',
    subtitle: 'Animal-Shaped Gentle Soap Collection',
    slug: 'little-explorers-animal-set',
    category: 'Gift Sets & Bundles',
    categoryId: 5,
    price: 399.00,
    originalPrice: 450.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_11.jpg',
    badge: 'Special · Kids',
    rating: 4.5,
    reviewCount: 24,
    scentProfile: 'Mild Coconut, Gentle Sweet Essence',
    skinType: 'All skin types',
    description: 'A cheerful set of animal-shaped soaps designed to make bath time a little more fun.',
    isActive: true,
  },
  {
    id: 'p-012',
    title: 'Herbarium Pressed Botanical Bar',
    subtitle: 'Encased Viola Pansies & Rosemary',
    slug: 'herbarium-pressed-botanical-bar',
    category: 'Floral & Rose',
    categoryId: 2,
    price: 469.00,
    originalPrice: 520.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_20.jpg',
    badge: 'Artisan Floral',
    rating: 5.0,
    reviewCount: 38,
    scentProfile: 'Pure Lavender Oil, Rosemary, Pressed Viola',
    skinType: 'All skin types',
    description: 'Handcrafted crystal-clear botanical soaps encasing real pressed pansies and fragrant herbs in glass-like clarity.',
    isActive: true,
  },
  {
    id: 'p-013',
    title: 'Relax & Enjoy Spa Ritual Box',
    subtitle: 'Honeycomb Bar, Bath Salt & Sisal Crate',
    slug: 'relax-enjoy-spa-ritual-box',
    category: 'Gift Sets & Bundles',
    categoryId: 5,
    price: 899.00,
    originalPrice: 999.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_21.jpg',
    badge: 'Deluxe Gift Box',
    rating: 5.0,
    reviewCount: 52,
    scentProfile: 'Wild Honey, Rose Petal, Himalayan Salt',
    skinType: 'Dry, sensitive & normal skin',
    description: 'A luxurious self-care crate featuring honeybee honeycomb soap, carved rose & daisy bars, botanical bath crystals, waffle towel, and natural sisal sponge.',
    isActive: true,
  },
  {
    id: 'p-014',
    title: 'Ocean Breeze Sea Turtle Gift Box',
    subtitle: 'Aquamarine Sea Turtle & Seashell Soaps',
    slug: 'ocean-breeze-sea-turtle-gift-box',
    category: 'Gift Sets & Bundles',
    categoryId: 5,
    price: 799.00,
    originalPrice: 899.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_22.jpg',
    badge: 'Curated Gift Box',
    rating: 5.0,
    reviewCount: 44,
    scentProfile: 'Marine Botanical Fragrance, Coconut Sea Minerals',
    skinType: 'All skin types',
    description: 'A charming coastal gift set featuring an aquamarine sea turtle soap nestled with pastel artisan seashells and tied with natural jute twine.',
    isActive: true,
  },
  {
    id: 'p-015',
    title: 'Ocean Seashore Crystal Wave Bar',
    subtitle: 'Deep Teal Swirling Sea Foam & Starfish',
    slug: 'ocean-seashore-crystal-wave-bar',
    category: 'Exfoliating & Purifying',
    categoryId: 3,
    price: 429.00,
    originalPrice: 489.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_23.jpg',
    badge: 'Special Edition',
    rating: 4.5,
    reviewCount: 31,
    scentProfile: 'Sea Kelp Extract, Ocean Breeze Oils',
    skinType: 'Normal to oily skin',
    description: 'Deep ocean teal glycerin soap bars poured with swirling sea foam, embedded shells, and a golden starfish.',
    isActive: true,
  },
  {
    id: 'p-016',
    title: 'Rustic Artisan Favor & Dish Set',
    subtitle: 'Cold-Processed Bar + Wooden Tray + Sisal',
    slug: 'rustic-artisan-favor-dish-set',
    category: 'Botanical Herbal',
    categoryId: 1,
    price: 549.00,
    originalPrice: 599.00,
    weightGrams: 200,
    stockQuantity: 100,
    imageUrl: '/images/soap_24.jpg',
    badge: 'Artisan Set',
    rating: 5.0,
    reviewCount: 49,
    scentProfile: 'Cedar & Amber Essential Oils, Raw Shea',
    skinType: 'All skin types',
    description: 'Cold-processed handmade soap bar in an organza keepsake pouch with a slotted wooden drainage tray and natural sisal scrub pad.',
    isActive: true,
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'ord-101',
    orderNumber: '#192541',
    flagged: true,
    customerName: 'Esther Howard',
    customerInitials: 'EH',
    customerEmail: 'esther.howard@example.com',
    customerPhone: '+1 (415) 555-2671',
    type: 'Shipping',
    shippingAddress: '742 Evergreen Terrace, Apt 4B',
    shippingCity: 'Portland, OR',
    shippingPostalCode: '97201',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 127.00,
    shippingFee: 0.00,
    totalAmount: 127.00,
    productThumbnails: ['/slide1.jpg', '/slide 2.jpg'],
    items: [
      { id: 1, title: 'Woodland Botanical Bar', quantity: 3, unitPrice: 14.00, totalPrice: 42.00, image: '/slide1.jpg' },
      { id: 2, title: 'Pink Himalayan Rose Bar', quantity: 2, unitPrice: 15.50, totalPrice: 31.00, image: '/slide 4.jpg' },
      { id: 3, title: 'Wild Herbal & Slate Bar', quantity: 3, unitPrice: 18.00, totalPrice: 54.00, image: '/slide 2.jpg' },
    ],
    date: 'Jun 19',
    createdAt: '2026-06-19T10:15:00Z'
  },
  {
    id: 'ord-102',
    orderNumber: '#192540',
    flagged: false,
    customerName: 'David Miller',
    customerInitials: 'DM',
    customerEmail: 'david.miller@example.com',
    customerPhone: '+1 (206) 555-9014',
    type: 'Pickups',
    shippingAddress: 'Botanical Atelier Pickup Hub #2',
    shippingCity: 'Seattle, WA',
    shippingPostalCode: '98101',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 94.50,
    shippingFee: 0.00,
    totalAmount: 94.50,
    productThumbnails: ['/slide 3.jpg', '/slide 5.jpg'],
    items: [
      { id: 4, title: 'Amber Honey & Saffron Bar', quantity: 3, unitPrice: 16.50, totalPrice: 49.50, image: '/slide 5.jpg' },
      { id: 5, title: 'Botanical Garden Spectrum', quantity: 3, unitPrice: 15.00, totalPrice: 45.00, image: '/slide 3.jpg' },
    ],
    date: 'Jun 19',
    createdAt: '2026-06-19T09:30:00Z'
  },
  {
    id: 'ord-103',
    orderNumber: '#192539',
    flagged: true,
    customerName: 'James Moore',
    customerInitials: 'JM',
    customerEmail: 'brodrigues@gmail.com',
    customerPhone: '+1 (415) 555-2671',
    type: 'Shipping',
    shippingAddress: '1490 Mission St, Suite 400',
    shippingCity: 'San Francisco, CA',
    shippingPostalCode: '94103',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 1927.89,
    shippingFee: 0.00,
    totalAmount: 1927.89,
    productThumbnails: ['/slide 4.jpg', '/slide1.jpg', '/slide 5.jpg'],
    items: [
      { id: 6, title: 'Artisan Master Botanical Gift Set (12 pcs)', quantity: 1, unitPrice: 1590.00, totalPrice: 1590.00, image: '/slide 4.jpg' },
      { id: 7, title: 'Botanical Essential Distiller & Diffuser', quantity: 1, unitPrice: 337.89, totalPrice: 337.89, image: '/slide 5.jpg' },
    ],
    date: 'Jun 19',
    createdAt: '2026-06-19T08:45:00Z'
  },
  {
    id: 'ord-104',
    orderNumber: '#192538',
    flagged: false,
    customerName: 'Robert Anderson',
    customerInitials: 'RA',
    customerEmail: 'robert.a@example.com',
    customerPhone: '+1 (512) 555-3401',
    type: 'Shipping',
    shippingAddress: '88 Meadowlane Boulevard',
    shippingCity: 'Austin, TX',
    shippingPostalCode: '78701',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 62.00,
    shippingFee: 0.00,
    totalAmount: 62.00,
    productThumbnails: ['/slide 2.jpg'],
    items: [
      { id: 8, title: 'Wild Herbal & Slate Bar', quantity: 2, unitPrice: 15.00, totalPrice: 30.00, image: '/slide 2.jpg' },
      { id: 9, title: 'Botanical Garden Spectrum', quantity: 2, unitPrice: 16.00, totalPrice: 32.00, image: '/slide 3.jpg' },
    ],
    date: 'Jun 19',
    createdAt: '2026-06-19T07:20:00Z'
  },
  {
    id: 'ord-105',
    orderNumber: '#192537',
    flagged: false,
    customerName: 'Jessica Martinez',
    customerInitials: 'JM',
    customerEmail: 'jessica.m@example.com',
    customerPhone: '+1 (303) 555-7788',
    type: 'Shipping',
    shippingAddress: '450 Sunset Dr',
    shippingCity: 'Boulder, CO',
    shippingPostalCode: '80302',
    status: 'REFUNDED',
    paymentStatus: 'REFUNDED',
    subtotal: 48.00,
    shippingFee: 0.00,
    totalAmount: 48.00,
    productThumbnails: ['/slide1.jpg'],
    items: [
      { id: 10, title: 'Woodland Botanical Bar', quantity: 3, unitPrice: 16.00, totalPrice: 48.00, image: '/slide1.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T16:20:00Z'
  },
  {
    id: 'ord-106',
    orderNumber: '#192536',
    flagged: false,
    customerName: 'William Jackson',
    customerInitials: 'WJ',
    customerEmail: 'w.jackson@example.com',
    customerPhone: '+1 (617) 555-1122',
    type: 'Shipping',
    shippingAddress: '32 Commonwealth Ave',
    shippingCity: 'Boston, MA',
    shippingPostalCode: '02116',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 185.00,
    shippingFee: 0.00,
    totalAmount: 185.00,
    productThumbnails: ['/slide 5.jpg', '/slide 4.jpg'],
    items: [
      { id: 11, title: 'Amber Honey & Saffron Bar', quantity: 5, unitPrice: 16.50, totalPrice: 82.50, image: '/slide 5.jpg' },
      { id: 12, title: 'Pink Himalayan Rose Bar', quantity: 5, unitPrice: 20.50, totalPrice: 102.50, image: '/slide 4.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T14:10:00Z'
  },
  {
    id: 'ord-107',
    orderNumber: '#192535',
    flagged: true,
    customerName: 'Christopher Harris',
    customerInitials: 'CH',
    customerEmail: 'c.harris@example.com',
    customerPhone: '+1 (312) 555-4490',
    type: 'Pickups',
    shippingAddress: 'Botanical Atelier Pickup Hub #1',
    shippingCity: 'Chicago, IL',
    shippingPostalCode: '60601',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 310.00,
    shippingFee: 0.00,
    totalAmount: 310.00,
    productThumbnails: ['/slide 2.jpg', '/slide 3.jpg'],
    items: [
      { id: 13, title: 'Botanical Garden Spectrum', quantity: 10, unitPrice: 16.00, totalPrice: 160.00, image: '/slide 3.jpg' },
      { id: 14, title: 'Wild Herbal & Slate Bar', quantity: 10, unitPrice: 15.00, totalPrice: 150.00, image: '/slide 2.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T12:00:00Z'
  },
  {
    id: 'ord-108',
    orderNumber: '#192534',
    flagged: false,
    customerName: 'Marcus Kenter',
    customerInitials: 'MK',
    customerEmail: 'm.kenter@example.com',
    customerPhone: '+1 (404) 555-8833',
    type: 'Shipping',
    shippingAddress: '102 Peachtree St',
    shippingCity: 'Atlanta, GA',
    shippingPostalCode: '30303',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 75.00,
    shippingFee: 0.00,
    totalAmount: 75.00,
    productThumbnails: ['/slide1.jpg'],
    items: [
      { id: 15, title: 'Woodland Botanical Bar', quantity: 5, unitPrice: 15.00, totalPrice: 75.00, image: '/slide1.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T10:45:00Z'
  },
  {
    id: 'ord-109',
    orderNumber: '#192533',
    flagged: false,
    customerName: 'Joshua Thompson',
    customerInitials: 'JT',
    customerEmail: 'j.thompson@example.com',
    customerPhone: '+1 (602) 555-6677',
    type: 'Shipping',
    shippingAddress: '55 Desert Palm Way',
    shippingCity: 'Phoenix, AZ',
    shippingPostalCode: '85001',
    status: 'CANCELLED',
    paymentStatus: 'FAILED',
    subtotal: 92.00,
    shippingFee: 0.00,
    totalAmount: 92.00,
    productThumbnails: ['/slide 4.jpg'],
    items: [
      { id: 16, title: 'Pink Himalayan Rose Bar', quantity: 4, unitPrice: 23.00, totalPrice: 92.00, image: '/slide 4.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T09:15:00Z'
  },
  {
    id: 'ord-110',
    orderNumber: '#192532',
    flagged: true,
    customerName: 'Megan Martin',
    customerInitials: 'MM',
    customerEmail: 'megan.martin@example.com',
    customerPhone: '+1 (214) 555-3344',
    type: 'Shipping',
    shippingAddress: '800 Main Street',
    shippingCity: 'Dallas, TX',
    shippingPostalCode: '75201',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 1528.60,
    shippingFee: 0.00,
    totalAmount: 1528.60,
    productThumbnails: ['/slide 5.jpg', '/slide 2.jpg', '/slide 3.jpg'],
    items: [
      { id: 17, title: 'Artisan Soap Workshop Collector Edition', quantity: 1, unitPrice: 1200.00, totalPrice: 1200.00, image: '/slide 5.jpg' },
      { id: 18, title: 'Amber Honey & Saffron Bar', quantity: 12, unitPrice: 16.50, totalPrice: 198.00, image: '/slide 5.jpg' },
      { id: 19, title: 'Wild Herbal & Slate Bar', quantity: 8, unitPrice: 16.32, totalPrice: 130.60, image: '/slide 2.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T08:00:00Z'
  },
  {
    id: 'ord-111',
    orderNumber: '#192531',
    flagged: false,
    customerName: 'Daniel Garcia',
    customerInitials: 'DG',
    customerEmail: 'd.garcia@example.com',
    customerPhone: '+1 (305) 555-9988',
    type: 'Shipping',
    shippingAddress: '120 Ocean Drive',
    shippingCity: 'Miami, FL',
    shippingPostalCode: '33139',
    status: 'PAID',
    paymentStatus: 'PAID',
    subtotal: 158.00,
    shippingFee: 0.00,
    totalAmount: 158.00,
    productThumbnails: ['/slide1.jpg', '/slide 4.jpg'],
    items: [
      { id: 20, title: 'Woodland Botanical Bar', quantity: 5, unitPrice: 14.00, totalPrice: 70.00, image: '/slide1.jpg' },
      { id: 21, title: 'Pink Himalayan Rose Bar', quantity: 5, unitPrice: 17.60, totalPrice: 88.00, image: '/slide 4.jpg' },
    ],
    date: 'Jun 18',
    createdAt: '2026-06-18T07:15:00Z'
  }
];

export const INITIAL_USERS = [
  {
    id: 'usr-001',
    email: 'admin@sageandbloom.com',
    firstName: 'Sage',
    lastName: 'Admin',
    fullName: 'Sage Admin',
    role: 'ROLE_SUPER_ADMIN',
    status: 'ACTIVE',
    createdAt: '2026-01-15T08:00:00Z',
    ordersCount: 0,
    totalSpent: 0
  },
  {
    id: 'usr-002',
    email: 'elena.rostova@example.com',
    firstName: 'Elena',
    lastName: 'Rostova',
    fullName: 'Elena Rostova',
    role: 'ROLE_CUSTOMER',
    status: 'ACTIVE',
    createdAt: '2026-04-10T11:20:00Z',
    ordersCount: 4,
    totalSpent: 182.50
  },
  {
    id: 'usr-003',
    email: 'marcus.v@example.com',
    firstName: 'Marcus',
    lastName: 'Vance',
    fullName: 'Marcus Vance',
    role: 'ROLE_CUSTOMER',
    status: 'ACTIVE',
    createdAt: '2026-05-18T14:10:00Z',
    ordersCount: 2,
    totalSpent: 98.00
  },
  {
    id: 'usr-004',
    email: 'staff.operations@sageandbloom.com',
    firstName: 'Oliver',
    lastName: 'Grant',
    fullName: 'Oliver Grant',
    role: 'ROLE_ADMIN',
    status: 'ACTIVE',
    createdAt: '2026-03-01T09:00:00Z',
    ordersCount: 0,
    totalSpent: 0
  }
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'log-001',
    actorEmail: 'admin@sageandbloom.com',
    action: 'EXPORT_ORDERS_CSV',
    resourceType: 'ORDER',
    resourceId: 'BATCH_5_ORDERS',
    ipAddress: '192.168.1.10',
    details: 'Exported 5 selected orders to CSV format with sanitized PII',
    result: 'SUCCESS',
    timestamp: '2026-09-22T14:12:00Z'
  },
  {
    id: 'log-002',
    actorEmail: 'admin@sageandbloom.com',
    action: 'PII_REVEAL_ATTEMPT',
    resourceType: 'CUSTOMER_DATA',
    resourceId: 'ord-103',
    ipAddress: '192.168.1.10',
    details: 'Admin revealed customer phone & email for Order #192539',
    result: 'SUCCESS',
    timestamp: '2026-09-22T13:45:00Z'
  },
  {
    id: 'log-003',
    actorEmail: 'admin@sageandbloom.com',
    action: 'PRODUCT_UPDATED',
    resourceType: 'PRODUCT',
    resourceId: 'p-001',
    ipAddress: '192.168.1.10',
    details: 'Updated price to $14.00 and stock to 42',
    result: 'SUCCESS',
    timestamp: '2026-09-22T11:05:00Z'
  },
  {
    id: 'log-004',
    actorEmail: 'admin@sageandbloom.com',
    action: 'USER_ROLE_CHANGED',
    resourceType: 'USER',
    resourceId: 'usr-004',
    ipAddress: '192.168.1.10',
    details: 'Promoted user Oliver Grant to ROLE_ADMIN',
    result: 'SUCCESS',
    timestamp: '2026-09-21T15:40:00Z'
  },
  {
    id: 'log-005',
    actorEmail: 'admin@sageandbloom.com',
    action: 'CATEGORY_CREATED',
    resourceType: 'CATEGORY',
    resourceId: '5',
    ipAddress: '192.168.1.10',
    details: 'Created category: Gift Sets & Bundles',
    result: 'SUCCESS',
    timestamp: '2026-09-20T10:15:00Z'
  }
];
